### ISSUE TITLE
Update to recent node versions

### ISSUE THREAD

**Issue by Kylart** [fanatid/libtorrent-rasterbar#13]
Hello,

Thanks for making these bindings. Unfortunately, I am not able to build this package, even with lower node version (I tried 4, 6 and 7 with no success). I am on Mac if that matters.

Is it possible to update this package to node 10/12?

If this package is no longer maintained, please just tell me and I'll try to work it off.

I would love to have an easy to use libtorrent bindings package 😄 

Thanks

**Comment by fanatid** [comment]
Hi, this is not longer maintained. I'd recommend to use [n-api](https://nodejs.org/api/n-api.html) if you want update package.

**Comment by Kylart** [comment]
Alright, I'll see what I can do then. Hopefully I can use some of this codebase as a start 😄
