### ISSUE TITLE
add_magnet_uri

### ISSUE THREAD

**Issue by bearburger** [fanatid/libtorrent-rasterbar#3]
Привет, Кирилл

Во-первых, спасибо за обёртку. А во-вторых, хотел поинтересоваться, насколько сложно добавить поддержку [add_magnet_uri](https://github.com/libtorrent/libtorrent/blob/d11376bbe3bae1d620bfba7f2d0d319bca556c90/include/libtorrent/magnet_uri.hpp)? Я слишком далёк от вопросов использования C++ в node и просто не понимаю, каким образом можно этот кусок вызвать из Node.

**Comment by maboiteaspam** [comment]
Hello,

try this,

```
var lt, main, s, th, ti;

lt = require("node-libtorrent/build/Release/libtorrent");

s = new lt.session();

s.start_dht();
s.listen_on([6881, 6889]);

var magnet = "magnet:?some real magnet";

th = s.add_torrent({
  url: magnet,
  save_path: "./test_magnet"
});

main = function() {
  var st;
  st = th.status();
  console.log("" + (st.progress * 100) + " complete (down: " + (st.download_rate / 1000) + " kb/s | up: " + (st.upload_rate / 1000) + " kB/s | peers: " + st.num_peers + ")");
  var alerts = s.pop_alerts();
  if( alerts.length ) console.log(alerts);
  return setTimeout(main, 500);
};

main();
```

**Comment by fanatid** [comment]
Так смешно видеть вопрос на русском и ответ на английском :)
@bearburger добавить не сложно, но библиотека устарела + вопросу 3 года
ещё можно добавить без написания c++ кода, через session::add_torrent (как заметил @maboiteaspam) какие параметры можно посмотреть тут -- https://github.com/arvidn/libtorrent/blob/libtorrent-1_1_1/src/magnet_uri.cpp#L179

**Comment by bearburger** [comment]
@fanatid ну, спустя три года, как бы уже и мне не нужно :-)
