### ISSUE TITLE
mac os error

### ISSUE THREAD

**Issue by hktalent** [fanatid/libtorrent-rasterbar#9]
xx

**Comment by 0181532686cf4a31163be0bf3e6bb6732bf** [comment]
Hi @hktalent ! I've made a fork of this with lots of improvements, please visit https://github.com/lyssdod/node-libtorrent

**Comment by fanatid** [comment]
@lyssdod thank you that rewrite this package on `nan`, but honestly I think that bindings for such big library should be autogenerated.. otherwise we will roll a boulder like Sisyphus :(

**Comment by 0181532686cf4a31163be0bf3e6bb6732bf** [comment]
What's Sisyphus? I know only club in Berlin :D

**Comment by fanatid** [comment]
https://en.wikipedia.org/wiki/Sisyphus :)

**Comment by 0181532686cf4a31163be0bf3e6bb6732bf** [comment]
Oh, in that sense :) I thought there's some software library which generates bindings...
